data:
  info: '../data/clean_data/info.csv'
  orders: '../data/raw_data/orders.csv'
  orders_prior: '../data/raw_data/order_products__prior.csv'
  instacart_sample: '../data/clean_data/instacart_sample.csv'
  instacart_labels: '../data/clean_data/instacart_labels.csv'

scalers:
  minmax: '../scalers/minmaxscaler.pickle'

encoders:
  ohe: '../encoders/ohe.pickle'

models:
  kmeans_randomstate: 1234
  kmeans_path: '../models/kmeans_scaled_'
  kmeans_path_k: '../models/kmeans_scaled_3.pickle'